site_name: AlignAI

  
theme:
  name: material
 # custom_dir: material/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - 首页: "index.md"
  - 研报: 
      - 图像去雾: "research/图像去雾算法研究_.md"
      - Google MedGemma: "research/Google MedGemma.md"
      - 点云转CAD: "research/点云转CAD.md"
      - 倾斜摄影:
        - 单目重建: "research/倾斜摄影单目重建.md"
  - 项目: 
      - MASt3R-SLAM: "projects/MASt3R-SLAM.md"
  - "license.md"