site_name: AlignAI

  
theme:
  name: material
 # custom_dir: material/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - "index.md"
  - 研报: 
      - 图像去雾: "research/图像去雾算法研究_.md"
      - Google MedGemma: "research/Google MedGemma.md"
      - 点云转CAD: "research/点云转CAD.md"
  - 项目: "about.md"
  - "license.md"